### ISSUE TITLE
Passed in the wrong options, column won't mark the job is 'Failed'

### ISSUE THREAD

**Issue by fredvong** [vmware/column#148]
**From the column container output**
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/column-0.5.0-py2.7.egg/column/api/manager/run_manager.py", line 86, in _run_playbook
    **options)
  File "/usr/local/lib/python2.7/dist-packages/column-0.5.0-py2.7.egg/column/api_runner.py", line 78, in run_playbook
    options = self._build_opt_dict(inventory_file, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/column-0.5.0-py2.7.egg/column/api_runner.py", line 200, in _build_opt_dict
    param='tag')
InvalidParameter: Invalid type of NoneType on parameter tag

**Output pulling from the CLI**
root@8b294d0ff58d:/app# http GET http://127.0.0.1:48620/runs/fa99f5fb-2eee-4231-9fcf-aa56b5e52796
HTTP/1.0 200 OK
Content-Length: 330
Content-Type: application/json
Date: Sat, 05 Aug 2017 06:04:05 GMT
Server: Werkzeug/0.12.2 Python/2.7.12

{
    "id": "fa99f5fb-2eee-4231-9fcf-aa56b5e52796", 
    "inventory_file": "/app/ansible_sddc/inventory", 
    "options": {
        "become_pass": "***", 
        "become_user": null, 
        "extra_vars": null, 
        "private_key_file": "/root/.ssh/.ssh/id_rsa", 
        "subset": null, 
        "tags": null
    }, 
    "playbook_path": "/app/ansible_sddc/site.yml", 
    "progress": 0, 
    "state": "RUNNING"
}

The 'state' will be stuck as 'RUNNING'.

**Comment by ushergod** [comment]
https://github.com/vmware/column/pull/151

**Comment by ericwb** [comment]
Fixed with pull request #151
