### ISSUE TITLE
Running column API fails

### ISSUE THREAD

**Issue by ericwb** [vmware/column#52]
```
browne-m01:column` browne$ python column/api/run.py 
Traceback (most recent call last):
  File "column/api/run.py", line 22, in <module>
    log_file = cfg.get('DEFAULT', 'log_file')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'log_file' in section: 'DEFAULT'
```

**Comment by ushergod** [comment]
https://github.com/vmware/column/pull/53/commits

**Comment by ericwb** [comment]
This was fixed, but running the API on Mac OSX results in this failure (although we don't technically support OSX).

```
browne-m01:column browne$ python column/api/run.py 
Traceback (most recent call last):
  File "column/api/run.py", line 27, in <module>
    level=log_level)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/column.log'
```
