### ISSUE TITLE
GET on http://10.20.140.104:48620/credentials with no body results in error 500

### ISSUE THREAD

**Issue by ericwb** [vmware/column#61]
GET on http://10.20.140.104:48620/credentials with no body results in error 500

```
10.166.17.40 - - [20/Jul/2017 16:09:19] "GET /runs/f7675ca1-08cd-4037-8da5-90a44c577c9 HTTP/1.1" 404 -
[2017-07-20 16:15:45,881] ERROR in app: Exception on /credentials [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/column-0.3.6-py2.7.egg/column/api/controller/credential_controller.py", line 29, in get
    cred = self.manager.get_credential(cred_payload)
  File "/usr/local/lib/python2.7/dist-packages/column-0.3.6-py2.7.egg/column/api/manager/credential_manager.py", line 21, in get_credential
    return utils.vault_decrypt(cred['value'])
TypeError: 'NoneType' object has no attribute '__getitem__'
10.166.17.40 - - [20/Jul/2017 16:15:45] "GET /credentials HTTP/1.1" 500 -
```

**Comment by ushergod** [comment]
https://github.com/vmware/column/pull/62
